- name: Check current version.
  become: true
  command: hub --version
  register: hub_current_version
  changed_when: false
  failed_when: false

- block:
    - name: Delete existing hub version if it's different.
      become: true
      file:
        path: /usr/local/bin/hub
        state: absent

    - name: Install
      become: true
      unarchive:
        src: https://github.com/github/hub/releases/download/v{{ hub_version }}/hub-linux-amd64-{{ hub_version }}.tgz
        dest: /usr/local/bin
        extra_opts: # https://github.com/ansible/ansible/issues/27081
          - --strip=2
          - --wildcards
          - '*/bin/hub'
        remote_src: yes

    - name: Add aliases
      become: true
      copy:
        dest: /etc/profile.d/hub.sh
        mode: 0644
        content: |
          eval "$(/usr/local/bin/hub alias -s)"
  when: hub_version not in hub_current_version.stdout | default('')
