---
- name: Check version to know if an update is needed or not
  command: '/opt/mutagen/mutagen version'
  register: mutagen_installed_version
  changed_when: mutagen_version not in mutagen_installed_version.stdout | default('')
  failed_when: False

- block:
    - name: Download
      get_url:
        url: https://github.com/mutagen-io/mutagen/releases/download/v{{ mutagen_version }}/mutagen_linux_amd64_v{{ mutagen_version }}.tar.gz
        dest: /tmp/mutagen.tar.gz
        force: yes

    - name: Create opt directory
      become: yes
      file:
        path: /opt/mutagen
        state: directory
        mode: 0755
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: Install
      unarchive:
        src: /tmp/mutagen.tar.gz
        dest: /opt/mutagen
        remote_src: yes

    - name: Add to PATH
      become: yes
      copy:
        dest: /etc/profile.d/mutagen.sh
        mode: 0644
        content: |
          export PATH="${PATH}:/opt/mutagen"
  when: mutagen_version not in mutagen_installed_version.stdout | default('')
