---
- name: Install peek repository
  become: yes
  apt_repository:
    repo: ppa:peek-developers/stable

- name: Install DBeaver repository
  become: yes
  apt_repository:
    repo: ppa:serge-rider/dbeaver-ce

- name: Install Yubico repository
  become: yes
  apt_repository:
    repo: ppa:yubico/stable

- name: vscode | Set gpg key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    state: present

- name: vscode | Add repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
    state: present
    update_cache: no

- name: insomnia | Set gpg key
  become: true
  apt_key:
    url: https://insomnia.rest/keys/debian-public.key.asc
    state: present

- name: insomnia | Add repository
  become: true
  apt_repository:
    repo: 'deb https://dl.bintray.com/getinsomnia/Insomnia /'
    filename: insomnia
    state: present
    update_cache: no

- name: Upgrade packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Install packages
  become: yes
  apt:
    cache_valid_time: 3600
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - man
      - linux-generic-hwe-18.04
      - xserver-xorg-hwe-18.04
      - lnav
      - stress
      - meld
      - bash-completion
      - screenfetch
      - htop
      - nmon
      - hdparm
      - smartmontools
      - sysbench
      - iotop
      - fio
      - multitail
      - git
      - git-extras
      - ssh
      - vim
      - vim-gui-common
      - zsh
      - tar
      - fonts-hack
      - unzip
      - netstat-nat
      - net-tools
      - powerline
      - tmux
      - openvpn
      - openssl
      - network-manager-openvpn-gnome
      - resolvconf
      - tzdata
      - locales
      - shellcheck
      - gnome-tweak-tool
      - gnome-shell-extensions
      - menulibre
      - apt-transport-https
      - ca-certificates
      - curl
      - imagemagick
      - gthumb
      - nautilus-image-converter
      - gir1.2-gtop-2.0
      - gir1.2-networkmanager-1.0
      - arc-theme
      - python-pip
      - ubuntu-make
      - keychain
      - postfix
      - mailutils
      - python-jmespath
      - ncdu
      - pandoc
      - libnss3-tools
      - peek
      - keepassxc
      - keepass2
      - gnupg2
      - entr
      - code
      - gdebi
      - chromium-browser
      - fonts-roboto
      - insomnia
      - dbeaver-ce
      - libpam-u2f
      - yubioath-desktop
      - wondershaper
      - chrome-gnome-shell
      - flameshot
      - jq
      - vlc

- name: Apply gnome config
  shell: |
    set -x

    # Reset shortcut for screenshot
    gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot ''

    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

    # Use flameshot for screenshot and bind shortcut see https://askubuntu.com/questions/1036473/ubuntu-18-how-to-change-screenshot-application-to-flameshot
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'flameshot'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/flameshot gui'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'Print'

    # Set shortcut to mute mic
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name 'Toggle mic'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command 'amixer set Capture toggle'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding 'Mail'

- name: 'Ensure /usr/local/bin belongs to {{ ansible_user }}'
  become: yes
  file:
    path: /usr/local/bin
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes

- name: Install pip packages
  pip:
    name: '{{ packages }}'
    state: latest
    extra_args: --user
  vars:
    packages:
      - pip
      - awscli
      - s-tui

- name: Firefox dev | Check for existing install
  stat:
    path: '/home/{{ ansible_user }}/.local/share/umake/web/firefox-dev'
  register: firefox_dev
  changed_when: False

- name: Firefox dev | Install
  shell: umake web firefox-dev /home/{{ ansible_user }}/.local/share/umake/web/firefox-dev --lang en-US
  when: not firefox_dev.stat.exists

- name: Croncape | Check for existing croncape install
  stat:
    path: '/usr/local/bin/croncape'
  register: croncape_install
  changed_when: False

- name: Croncape | Check croncape version to know if an update is needed or not
  command: '/usr/local/bin/croncape --version'
  register: croncape_installed_version
  when: 'croncape_install.stat.exists'
  changed_when: 'croncape_version not in croncape_installed_version.stdout'
  failed_when: False

- block:
    - name: Croncape | Download croncape
      get_url:
        url: https://github.com/symfonycorp/croncape/releases/download/{{ croncape_version }}/croncape_linux_amd64.tar.gz
        checksum: 'sha256:{{ croncape_archive_checksum }}'
        dest: /tmp/croncape_linux_amd64.tar.gz
        force: yes

    - name: Croncape | Install croncape
      unarchive:
        src: /tmp/croncape_linux_amd64.tar.gz
        dest: '/usr/local/bin'
        remote_src: yes
  when: not croncape_install.stat.exists or croncape_version not in croncape_installed_version.stdout

- name: gitlab-runner | Check for existing gitlab-runner install
  command: 'which gitlab-runner'
  register: gitlab_runner_install
  changed_when: False
  ignore_errors: True

- block:
    - name: gitlab-runner | Download gitlab-runner repository script
      get_url:
        url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
        dest: /tmp/gitlab-script.deb.sh
        force: yes

    - name: gitlab-runner | Install gitlab-runner repository
      become: true
      shell: bash /tmp/gitlab-script.deb.sh
  when: gitlab_runner_install.failed

- name: gitlab-runner | Install
  become: yes
  apt:
    cache_valid_time: 3600
    name: gitlab-runner
    state: present

- name: mkcert | Check for existing mkcert install
  stat:
    path: '/usr/local/bin/mkcert'
  register: mkcert_install
  changed_when: False

- block:
    - name: mkcert | Download and install mkcert
      get_url:
        url: https://github.com/FiloSottile/mkcert/releases/download/{{ mkcert_version }}/mkcert-{{ mkcert_version }}-linux-amd64
        dest: /usr/local/bin/mkcert
        mode: 0755
        force: yes

    - name: mkcert | Create local CA
      shell: /usr/local/bin/mkcert -install
      register: mkcert_install
      changed_when: "'Created a new local CA' in mkcert_install.stdout"
  when: not mkcert_install.stat.exists

- name: fzf | Clone repository
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1

- name: fzf | Install
  shell: ~/.fzf/install --completion --64 --key-bindings --update-rc

- name: fd | Check for existing fd install
  stat:
    path: '/usr/bin/fd'
  register: fd_install
  changed_when: False

- name: fd | Check fd version to know if an update is needed or not
  command: '/usr/bin/fd --version'
  register: fd_installed_version
  when: 'fd_install.stat.exists'
  changed_when: 'fd_version not in fd_installed_version.stdout'
  failed_when: False

- block:
    - name: fd | Download and install
      become: yes
      apt:
        deb: https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd_{{ fd_version }}_amd64.deb
  when: not fd_install.stat.exists or fd_version not in fd_installed_version.stdout

- name: bat | Check for existing bat install
  stat:
    path: '/usr/bin/bat'
  register: bat_install
  changed_when: False

- name: bat | Check bat version to know if an update is needed or not
  command: '/usr/bin/bat --version'
  register: bat_installed_version
  when: 'bat_install.stat.exists'
  changed_when: 'bat_version not in bat_installed_version.stdout'
  failed_when: False

- block:
    - name: bat | Download and install
      become: yes
      apt:
        deb: https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_amd64.deb
  when: not bat_install.stat.exists or bat_version not in bat_installed_version.stdout

- name: slack | Check for existing slack install
  command: dpkg-query -W slack-desktop
  register: slack_installed
  failed_when: false
  changed_when: false

- block:
    - name: slack | Download and install
      become: yes
      apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb
  when: slack_installed.rc == 1

- name: discord | Check for existing discord install
  command: dpkg-query -W discord
  register: discord_installed
  failed_when: false
  changed_when: false

- block:
    - name: discord | Download and install
      become: yes
      apt:
        deb: https://discordapp.com/api/download?platform=linux&format=deb
  when: discord_installed.rc == 1

- name: vagrant | Check vagrant version to know if an update is needed or not
  command: '/usr/bin/vagrant --version'
  register: vagrant_installed_version
  changed_when: vagrant_installed_version is defined and vagrant_version not in vagrant_installed_version.stdout
  failed_when: False

- block:
    - name: vagrant | Download and install
      become: yes
      apt:
        deb: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
  when: vagrant_installed_version is defined and vagrant_version not in vagrant_installed_version.stdout

- name: keybase | Check for existing keybase install
  command: dpkg-query -W keybase
  register: keybase_installed
  failed_when: false
  changed_when: false

- block:
    - name: keybase | Download and install
      become: yes
      apt:
        deb: https://prerelease.keybase.io/keybase_amd64.deb
  when: keybase_installed.rc == 1

- name: Remove useless packages
  become: yes
  apt:
    purge: yes
    autoremove: yes

- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes

# Source https://github.com/sanduhrs/phpstorm-url-handler
- name: phpstorm-url-handler | Install shell script
  copy:
    src: phpstorm-url-handler
    dest: /usr/local/bin/phpstorm-url-handler

- name: phpstorm-url-handler | Install desktop file
  become: yes
  shell: 'desktop-file-install "{{ role_path}}/files/phpstorm-url-handler.desktop" && update-desktop-database'

- name: JetBrains Toolbox | Import jaredhocutt.jetbrains_toolbox
  import_role:
    name: jaredhocutt.jetbrains_toolbox

- name: JetBrains Toolbox | Create symbolic link to binary
  file:
    src: '/home/{{ ansible_user }}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox'
    dest: '/usr/local/bin/jetbrains-toolbox'
    state: link
