---
- name: Install packages
  become: true
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - lnav
      - stress
      - meld
      - bash-completion
      - screenfetch
      - htop
      - nmon
      - hdparm
      - smartmontools
      - sysbench
      - iotop
      - fio
      - multitail
      - git
      - git-extras
      - vim
      - zsh
      - tar
      - unzip
      - powerline
      - tmux
      - openvpn
      - openssl
      - resolvconf
      - ShellCheck
      - gnome-tweak-tool
      - ca-certificates
      - curl
      - nautilus-image-converter
      - postfix
      - ncdu
      - gnupg2
      - google-roboto-fonts
      - google-roboto-mono-fonts
      - flameshot
      - jq
      - vlc
      - exa # ls like: https://github.com/ogham/exa
      - ripgrep # grep like: https://github.com/BurntSushi/ripgrep
      - fd-find # find like: https://github.com/sharkdp/fd
      - bat # find like: https://github.com/sharkdp/bat
      - hyperfine # benchmarking: https://github.com/sharkdp/hyperfine
      - fzf # cli fuzzy search and more: https://github.com/junegunn/fzf
