---
- name: Main playbook to setup machine
  hosts: localhost
  gather_facts: yes
  vars:
    ansible_user: benoit
    jetbrains_toolbox_version: 1.11
  vars_files:
    - vault.yaml
  roles:
    - packages
    - user
    - repositories
    - docker
    - jaredhocutt.jetbrains_toolbox
      # php avec php-cs-fixer et composer
      # composer
      # install https://github.com/sanduhrs/phpstorm-url-handler
      # install https://github.com/sharkdp/bat
      # mkcert
      #  cozy cloud
      # install docs and learning-lab

# 19  cp hidden.extra ../
# 20  cp hidden.gitconfig_private ../.gitconfig_private
# 21  mv ../hidden.extra ../.extra
# 22  dconf load /org/gnome/ < gnome_settings_backup.txt
