---
- name: Main playbook to setup machine
  hosts: localhost
  gather_facts: yes
  gather_subset: [min]
  vars:
    ansible_user: benoit
    jetbrains_toolbox_version: latest
  vars_files:
    - vault.yaml
  roles:
    - user
    - system
    - software
    - repositories
    - rust
    - alacritty
    - php
    - docker
    - nodejs
#    - dbeaver
    - keepassxc
    - peek
    - vscode
    - yubico
    - spotify
    - unipdf-cli
    - stellar
    - slack
    - mkcert
    - croncape
    - hexyl
    - discord
    - keybase
    - gitlab-runner
    - jaredhocutt.jetbrains_toolbox
    - phpstorm-url-handler
    - firefox-dev
    - drawio
