---
- name: Main playbook to setup machine
  hosts: localhost
  gather_facts: yes
  gather_subset: [min]
  vars:
    ansible_user: benoit
    jetbrains_toolbox_version: 1.11
    croncape_version: v1.2.1
    croncape_archive_checksum: 28a5da07e6168799aae9e7aa656b5faa9694f3b915f40ffdac3c14991c26c409
    mkcert_version: v1.3.0
    fd_version: 7.1.0
    bat_version: 0.8.0
    slack_version: 3.3.3
    hexyl_version: 0.6.0
  vars_files:
    - vault.yaml
  roles:
    - role: software
      tags: [software]
#    - mutagen
    - keepassxc
    - peek
    - dbeaver
    - vscode
    - yubico
    - hyperfine
    - vagrant
    - spotify
    - hub
    - role: user
      tags: [user]
    - role: repositories
      tags: [repositories]
    - role: docker
      tags: [docker]
    - role: system
      tags: [system]
    - role: nodejs
      tags: [nodejs]
    - role: php
      tags: [php]
