---
- name: Main playbook to setup machine
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/vars.yml
  roles:
    - packages
    - user
    - dotfiles
    - docker
    # - docker + docker-dns-gen
      # install locale
      # install dropbox cryptomator + fstab entry, KeeWeb, php avec php-cs-fixer et composer
      # install jetbrains toolbox + phpstorm
      # composer
      # install https://github.com/sanduhrs/phpstorm-url-handler
      # install https://github.com/sharkdp/bat
      # gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
      # install apt://gnome-software-plugin-flatpak
      # mkcert
      # keychain
      #  cozy cloud
      # setup crontab

# 19  cp hidden.extra ../
# 20  cp hidden.gitconfig_private ../.gitconfig_private
# 21  mv ../hidden.extra ../.extra
# 22  dconf load /org/gnome/ < gnome_settings_backup.txt
