---
- name: Main playbook to setup machine
  hosts: localhost
  gather_facts: yes
  gather_subset: [min]
  vars:
    ansible_user: benoit
    jetbrains_toolbox_version: latest
    fd_version: 7.1.0
    bat_version: 0.8.0
    hexyl_version: 0.6.0
  vars_files:
    - vault.yaml
  pre_tasks:
    - name: Upgrade packages
      become: true
      apt:
        update_cache: true
        upgrade: true
  roles:
    - role: user
      tags: [user]
    - role: system
      tags: [system]
    - role: software
      tags: [software]
    - role: repositories
      tags: [repositories]
    - role: php
      tags: [php]
    - role: docker
      tags: [docker]
    - role: nodejs
      tags: [nodejs]
#    - mutagen
    - keepassxc
    - peek
    - dbeaver
    - vscode
    - yubico
    - hyperfine
    - vagrant
    - spotify
    - hub
    - insomnia
    - stellar
    - slack
    - mkcert
    - croncape
