---
- name: Install locales
  become: true
  package:
    name: locales
    state: present
  when: ansible_os_family == 'Debian'

- name: Install locales
  become: true
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - fr_FR.UTF-8

- name: Add ENV vars in /etc/profile.d/custom.sh
  become: true
  copy:
    dest: /etc/profile.d/custom.sh
    mode: 0644
    content: |
      PATH="$PATH:/snap/bin"
  when: ansible_os_family == 'Debian'

- name: Set LANG to en_US.UTF-8
  become: true
  shell: update-locale LANG=en_US.UTF-8
