---
- name: Upgrade packages
  become: yes
  apt: update_cache=yes upgrade=yes cache_valid_time=3600

- name: Install packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - man
    - bash-completion
    - screenfetch
    - htop
    - nmon
    - hdparm
    - smartmontools
    - sysbench
    - iotop
    - fio
    - multitail
    - git
    - vim
    - vim-gui-common
    - zsh
    - tar
    - unzip
    - netstat-nat
    - net-tools
    - powerline
    - tmux
    - tzdata
    - locales
    - gnome-tweak-tool
    - apt-transport-https
    - ca-certificates
    - curl
