---
- name: Upgrade packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Install packages
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - man
    - bash-completion
    - screenfetch
    - htop
    - nmon
    - hdparm
    - smartmontools
    - sysbench
    - iotop
    - fio
    - multitail
    - git
    - ssh
    - vim
    - vim-gui-common
    - zsh
    - tar
    - unzip
    - netstat-nat
    - net-tools
    - powerline
    - tmux
    - tzdata
    - locales
    - gnome-tweak-tool
    - gnome-shell-extensions
    - apt-transport-https
    - ca-certificates
    - curl
    - gir1.2-gtop-2.0
    - gir1.2-networkmanager-1.0
    - arc-theme
    - python-pip
    - keychain
    - postfix
    - mailutils
    - python-jmespath
    - ncdu
    - pandoc

- name: Install croncape
  become: yes
  unarchive:
      src: https://github.com/symfonycorp/croncape/releases/download/v1.2.1/croncape_linux_amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes
