---
- name: Create /etc/profile.d directory
  become: yes
  file:
    path: /etc/profile.d
    state: directory
    mode: 0755

- name: Import role geerlingguy.nodejs
  become: yes
  import_role:
    name: geerlingguy.nodejs
  vars:
    npm_config_prefix: '/home/{{ ansible_user }}/.npm-global'
    nodejs_version: 8.x
    nodejs_npm_global_packages: [doctoc]

- name: 'Ensure npm global belongs to {{ ansible_user }}'
  file:
    path: '~/.npm-global'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
