---
- name: Node | Create /etc/profile.d directory
  become: yes
  file:
    path: /etc/profile.d
    state: directory
    mode: 0755

- name: Node | Import role geerlingguy.nodejs
  become: yes
  import_role:
    name: geerlingguy.nodejs
  vars:
    npm_config_prefix: '/home/{{ ansible_user }}/.npm-global'
    nodejs_version: 10.x
    nodejs_npm_global_packages:
      - yarn
      - ngrok
      - doctoc
      - diff-so-fancy
      - tldr
      - prettier
      - npm
      - semantic-release-cli
      - semantic-release

- name: 'Node | Ensure npm global belongs to {{ ansible_user }}'
  become: yes
  file:
    path: '/home/{{ ansible_user }}/.npm-global'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes

- name: 'Node | Ensure npm cache belongs to {{ ansible_user }}'
  become: yes
  file:
    path: '/home/{{ ansible_user }}/.npm'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes

- name: 'Node | Remove NODE_PATH env variable'
  become: yes
  replace:
    path: /etc/profile.d/npm.sh
    regexp: '^export NODE_PATH=(.*)'
    replace: '#export NODE_PATH=\1'

- name: 'Node | Update global packages'
  shell: 'npm update -g'
