---
- name: Write /etc/sysctl.d/local.conf file
  become: yes
  notify: restart systemctl
  copy:
    dest: /etc/sysctl.d/local.conf
    content: |
      vm.swappiness=5
      # phpstorm
      fs.inotify.max_user_watches = 1048576
      net.ipv4.ip_forward=1
      vm.max_map_count=262144

- name: Write /etc/systemd/system/btsync@.service file
  become: yes
  notify: restart systemctl
  copy:
    dest: /etc/systemd/system/btsync@.service
    content: |
      [Unit]
      Description=BTSync for user %I
      Requires=network.target
      After=network.target

      [Service]
      Type=simple
      User=%I
      ExecStart=/usr/local/bin/btsync --config /home/%I/.sync/btsync.json --nodaemon

      [Install]
      WantedBy=multi-user.target
