---
- name: Set gpg key
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    state: present

- name: Add repository
  become: true
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'
    filename: spotify
    state: present

- name: Install
  become: true
  apt:
    name: [spotify-client]
