---
- name: slack | Check for existing slack install
  command: dpkg-query -W slack-desktop
  register: slack_installed
  failed_when: false
  changed_when: false

- block:
    - name: slack | Download and install
      become: true
      apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb
  when: slack_installed.rc == 1
