---
- name: Add GPG key
  become: true
  rpm_key:
    key: https://keybase.io/docs/server_security/code_signing_key.asc
    state: present

- name: Check if already installed
  become: true
  dnf:
    name: keybase
    state: present
  register: keybase_installed
  failed_when: false

- name: Install
  become: true
  dnf:
    name: https://prerelease.keybase.io/keybase_amd64.rpm
    state: present
  when: keybase_installed.rc == 1
