---
- name: Check if already installed
  become: true
  dnf:
    name: keybase
    state: present
  register: keybase_installed
  failed_when: false

# TODO lazy install
- name: Install
  become: true
  dnf:
    name: https://prerelease.keybase.io/keybase_amd64.rpm
    state: present
    disable_gpg_check: true
  when: keybase_installed.rc == 1
