---
- name: Check current docker-compose version.
  become: true
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- block:
    - name: Delete existing docker-compose version if it's different.
      become: true
      file:
        path: "{{ docker_compose_path }}"
        state: absent

    - name: Install Docker Compose
      become: true
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: "{{ docker_compose_path }}"
        mode: 0755
  when: docker_compose_version not in docker_compose_current_version.stdout | default('')
