---
- name: Remove bind9 if present
  become: yes
  failed_when: false
  apt:
    name: bind9
    state: absent

- name: Install dnsmasq
  become: yes
  apt:
    name: dnsmasq
    state: present

- name: Create /etc/docker directory
  become: yes
  file: 
    path: /etc/docker
    state: directory 
    mode: 0755

- name: /etc/docker/daemon.json
  become: yes
  notify: restart
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "dns": ["172.17.42.1"],
        "bip": "172.17.42.1/24"
      }

- name: Create /etc/systemd/system/docker.service.d directory
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory 
    mode: 0755

- name: /etc/systemd/system/docker.service.d/override.conf
  become: yes
  notify: restart
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Unit]
      Before=NetworkManager.service

- name: /etc/NetworkManager/conf.d/dns.conf
  become: yes
  notify: restart
  copy:
    dest: /etc/NetworkManager/conf.d/dns.conf
    content: |
      [main]
      dns=dnsmasq

- name: Install docker-py
  pip:
    name: docker-py
    state: present

- name: /etc/NetworkManager/dnsmasq.d/docker
  become: yes
  notify: restart
  copy:
    dest: /etc/NetworkManager/dnsmasq.d/docker
    content: |
      bind-interfaces
      interface=lo
      interface=docker0
      server=/docker/127.0.0.1#54
      address=/code/127.0.0.1

- name: Disable systemd-resolved
  become: yes
  notify: restart
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Disable dnsmasq
  become: yes
  notify: restart
  systemd:
    name: dnsmasq
    state: stopped
    enabled: no

- name: /etc/resolv.conf must point to /var/run/NetworkManager/resolv.conf
  become: yes
  notify: restart
  file:
    path: /etc/resolv.conf
    src: /var/run/NetworkManager/resolv.conf
    state: link
    follow: no
    force: yes

- name: Run docker-dns-gen
  docker_container:
    name: dns-gen
    image: jderusse/dns-gen
    command: -R
    restart_policy: always
    published_ports: ['54:53/udp']
    capabilities: [NET_BIND_SERVICE]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

