---
- name: Remove bind9 if present
  become: true
  failed_when: false
  apt:
    name: bind9
    state: absent

- name: Remove dnsmasq if present
  become: true
  failed_when: false
  apt:
    name: dnsmasq
    state: absent

- name: Install resolvconf
  become: true
  apt:
    name: resolvconf
    state: present

- name: Create /etc/docker directory
  become: true
  file: 
    path: /etc/docker
    state: directory 
    mode: 0755

- name: /etc/docker/daemon.json
  become: true
  notify: restart
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "bip": "172.17.42.1/24"
      }

- name: Create /etc/systemd/resolved.conf.d directory
  become: true
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: 0755

- name: /etc/systemd/resolved.conf.d/resolved.conf
  become: true
  notify: restart
  copy:
    dest: /etc/systemd/resolved.conf.d/resolved.conf
    content: |
      [Resolve]
      DNS=82.229.244.191 1.1.1.1

- name: /etc/resolvconf/resolv.conf.d/head
  become: true
  notify: restart
  copy:
    dest: /etc/resolvconf/resolv.conf.d/head
    content: |
      # Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
      #     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
      # 127.0.0.53 is the systemd-resolved stub resolver.
      # run "systemd-resolve --status" to see details about the actual nameservers.

      nameserver 172.17.42.1 # dns-gen

# This is for docker module of Ansible to work
- name: Install docker-py
  pip:
    name: docker-py
    state: latest
    extra_args: --user

- name: Run docker-dns-gen
  docker_container:
    name: dns-gen
    image: jderusse/dns-gen:2
    restart_policy: always
    log_options: max-size=10m
    log_driver: json-file
    network_mode: host
    env:
      GATEWAY: '172.17.42.1'
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
