---
- name: Add Docker apt key.
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository.
  become: true
  apt_repository:
    repo: "{{ apt_repository }}"
    state: present
    update_cache: yes

- name: install docker
  become: true
  apt:
    name: "docker-ce"
    force: yes

