---
- name: Set gpg key
  become: true
  apt_key:
    url: https://insomnia.rest/keys/debian-public.key.asc
    state: present

- name: Add repository
  become: true
  apt_repository:
    repo: 'deb https://dl.bintray.com/getinsomnia/Insomnia /'
    filename: insomnia
    state: present
    update_cache: false
