---
- name: Install php packages
  become: yes
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - php7.2-cli
    - php-redis
    - php7.2-common
    - php7.2-curl
    - php7.2-zip
    - php7.2-json
    - php7.2-mbstring
    - php7.2-opcache
    - php7.2-readline
    - php7.2-sqlite3
    - php7.2-xml

- name: Import role geerlingguy.composer
  import_role:
    name: geerlingguy.composer
  vars:
    composer_home_path: '~/.composer'
    composer_path: /usr/local/bin/composer
    composer_add_to_path: true
    composer_home_owner: '{{ ansible_user }}'
    composer_home_group: '{{ ansible_user }}'
    composer_keep_updated: true

- name: Ensure /etc/profile.d/composer.sh file is present
  become: yes
  copy:
      content: 'export PATH=$PATH:~/.composer/vendor/bin'
      dest: /etc/profile.d/composer.sh
      mode: 0644

- name: Write /etc/php/7.2/cli/conf.d/99-custom.ini file
  become: yes
  copy:
    dest: /etc/php/7.2/cli/conf.d/99-custom.ini
    content: |
      [PHP]
      error_reporting = E_ALL
      display_errors = On
      display_startup_errors = On
      log_errors = On
      log_errors_max_len = 1024
      report_memleaks = On
      default_charset = "UTF-8"

      [Date]
      date.timezone = Europe/Paris
