---
- import_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- import_tasks: composer.yaml
- import_tasks: symfony.yaml
#- import_tasks: phive.yaml
