---
- name: Check version to know if an update is needed or not
  command: '/usr/bin/drawio --version'
  register: drawio_installed_version
  changed_when: drawio_version not in drawio_installed_version.stdout | default('')
  failed_when: False

- block:
    - name: Add GPG key
      become: true
      rpm_key:
        key: https://packagecloud.io/jgraph/drawio/gpgkey
        state: present

    - name: Download and install
      become: true
      dnf:
        name: https://github.com/jgraph/drawio-desktop/releases/download/v{{ drawio_version }}/drawio-x86_64-{{ drawio_version }}.rpm
        state: latest
  when: drawio_version not in drawio_installed_version.stdout | default('')


