---
- name: Check version to know if an update is needed or not
  command: '/usr/bin/drawio --version'
  register: drawio_installed_version
  changed_when: drawio_version not in drawio_installed_version.stdout | default('')
  failed_when: False

- block:
    - name: Download and install
      become: true
      dnf:
        name: https://github.com/jgraph/drawio-desktop/releases/download/v{{ drawio_version }}/drawio-x86_64-{{ drawio_version }}.rpm
        state: latest
        disable_gpg_check: true
  when: drawio_version not in drawio_installed_version.stdout | default('')


