---
- name: fd | Check for existing fd install
  stat:
    path: '/usr/bin/fd'
  register: fd_install
  changed_when: False

- name: fd | Check fd version to know if an update is needed or not
  command: '/usr/bin/fd --version'
  register: fd_installed_version
  when: 'fd_install.stat.exists'
  changed_when: 'fd_version not in fd_installed_version.stdout'
  failed_when: False

- block:
    - name: fd | Download and install
      become: true
      apt:
        deb: https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd_{{ fd_version }}_amd64.deb
  when: not fd_install.stat.exists or fd_version not in fd_installed_version.stdout
